# Generated by Django 3.0.4 on 2020-03-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço')),
                ('phone', models.BigIntegerField(verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='passengers_photo', verbose_name='Foto')),
                ('evaluation', models.BooleanField(blank=True, default=True, null=True, verbose_name='Avaliação')),
                ('obs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
                'ordering': ['name'],
            },
        ),
    ]
